name: Unit Tests

on: [push]

env:
  MIN_COVERAGE_REQUIRED: 85

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Python 3.10.18
        uses: actions/setup-python@v1
        with:
            python-version: 3.10.18

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Github Action for testing the code
        run: |
          coverage run --source=./ -m pytest tests/
        

      - name: Github Action to retrieve coverage percentage
        id: total-coverage
        run: |
          coverage report
          coverage json -q -o /dev/stdout | python -c 'import sys, json; perc_cov = json.load(sys.stdin)["totals"]["percent_covered"]; is_covered = perc_cov >= '$MIN_COVERAGE_REQUIRED'; print(f"\nTotal Coverage is: {perc_cov:.2f}%"); sys.exit(not is_covered)'
